# -*- coding: utf-8 -*-
"""project_poo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/R5780/09159bccfc2381494cdd805cf283b48e/project_poo.ipynb
"""

from google.colab import files
uploaded = files.upload()

class DNASequence:
    def __init__(self, sequence, label=None):
        self.sequence = sequence.replace('\t', '')
        self.label = label
        self.encoded = None

    def one_hot_encode(self):
        mapping = {
            'A': [1, 0, 0, 0],
            'C': [0, 1, 0, 0],
            'G': [0, 0, 1, 0],
            'T': [0, 0, 0, 1]
        }
        self.encoded = []
        for nucleotide in self.sequence:
            self.encoded.extend(mapping.get(nucleotide, [0, 0, 0, 0]))
        return self.encoded

    def __str__(self):
        return f"DNASequence(sequence={self.sequence[:10]}..., label={self.label})"

import pandas as pd

# قراءة ملف CSV
df = pd.read_csv("dna_sequences.csv")

# التأكد من شكل البيانات
print(df.head())

# تحويل كل صف إلى كائن من نوع DNASequence
sequences = []
for i, row in df.iterrows():
    seq_str = ''.join(map(str, row[:-1]))
    label = row["Class"]
    seq_obj = DNASequence(seq_str, label)
    seq_obj.one_hot_encode()
    sequences.append(seq_obj)

print(f"عدد التسلسلات: {len(sequences)}")
print(sequences[0])

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

# تجهيز البيانات
X = np.array([s.encoded for s in sequences])
y = np.array([1 if s.label == '+' else 0 for s in sequences])

# تقسيم البيانات
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# تدريب النموذج
model = RandomForestClassifier()
model.fit(X_train, y_train)

# التقييم
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(x="Class", data=df)
plt.title("Répartition des classes")
plt.xlabel("Classe")
plt.ylabel("Nombre de séquences")
plt.show()

"""# Projet de Classification de Séquences ADN

## 🎯 Objectif
Ce projet a pour but d'analyser des séquences d'ADN et de prédire si elles sont des **promoteurs** ou non, en utilisant des algorithmes de Machine Learning et la programmation orientée objet (POO) en Python.

## 🧬 Données utilisées
Les données proviennent de [UCI Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Molecular+Biology+(Promoter+Gene+Sequences)).  
Elles contiennent **100 séquences ADN**, chacune de **57 nucléotides**, avec un label :
- `+` pour promoteur
- `-` pour non-promoteur

## ⚙️ Structure du projet
- `DNASequence` : une classe qui représente une séquence ADN avec encodage numérique.
- `ModelTrainer` (dans Colab) : pour entraîner et évaluer des modèles de classification.
- `main` : exécution de l’analyse complète dans Google Colab.

## 🧪 Méthodologie
- Importation et nettoyage des données
- One-hot encoding des séquences
- Entraînement de modèles (Random Forest)
- Évaluation par précision et rapport de classification

## 📊 Résultats
Le modèle Random Forest a obtenu une précision d’environ **XX%** (à compléter après exécution).  
Les résultats montrent que les séquences promoteurs ont un certain motif distinctif capté par le modèle.

## 📁 Fichiers fournis
- `dna_sequences.csv` : fichier CSV nettoyé
- Code complet dans un notebook `.ipynb`

## 🚀 Exécution
Ce projet a été réalisé entièrement dans **Google Colab**.

"""